sonar.projectKey=lpicanco_prometheus-speedtest-exporter
sonar.organization=lpicanco


# Path is relative to the sonar-project.properties file
sonar.sources=src
sonar.tests=tests

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Coverage report path
sonar.rust.coverage.reportPaths=lcov.info 